--- 
build: 
  dependencies: 
    before: 
      - "composer require phpunit/phpunit:^7.0 --dev"
  environment: 
    php: 
      version: 7.2
  tests: 
    - 
      override: 
        command: "vendor/bin/phpunit --coverage-clover=tests/testCoverage.xml"
        coverage: 
          file: clover.xml
          format: php-clover
checks: 
  javascript: true
  php: true
filter: 
  excluded_paths: 
    - "*.bundle.js"
    - "*.min.js"
    - "*/build/*"
    - "*/devServer/*"
    - "*/public/*"
    - "*/tests/*"
