filter:
    excluded_paths:
        - '*.bundle.js'
        - '*.min.js'
        - '*/build/*'
        - '*/devServer/*'
        - '*/public/*'
        - '*/tests/*'
checks:
    javascript: true
    php: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: false
